name: BuildAndTestOnEveryPush.yml

on:
  push:
    branches-ignore:
      - master

jobs:

  UbuntuBuild:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: build docker container
      run:  docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Salakala123!" -p 1433:1433 --name sql1 --hostname sql1 -d mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04

    - name: Build
      run: dotnet build

    - name: Run SaveQueryToCsvTests
      run: dotnet test --filter Frends.Community.SQL.Tests.SaveQueryToCSVTests

    - name: Run TestBulkInsert
      run: dotnet test --filter Frends.Community.SQL.Tests.TestBulkInsert

  WindowsBuild:
    needs: UbuntuBuild
    name: Build on windows-latest
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test
          
    - name: Pack release version of task
      run: dotnet pack --configuration Release --include-source
      
    - name: Push NuGet package to the testfeed
      run: dotnet nuget push Frends.Community.SQL\bin\Release\Frends.Community.SQL.*.nupkg  --api-key ${{ secrets.COMMUNITY_FEED_API_KEY }} --source https://www.myget.org/F/frends-community-test/api/v2/package
